---
name: 'Asset Crusher'
description: 'Compresses assets AND updates code references automatically.'
author: 'Alireza Feizi'
branding:
  icon: 'minimize-2'
  color: 'orange'

inputs:
  quality:
    description: 'WebP compression quality (0-100)'
    required: false
    default: '75'
  
  delete_original:
    description: 'Delete original files & update code references'
    required: false
    default: 'true'
  
  commit_message:
    description: 'Commit message'
    required: false
    default: 'chore: assets crushed & code refactored 🤖'

runs:
  using: "composite"
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg webp

    - name: Run Compression & Refactor Logic
      shell: bash
      env:
        INPUT_QUALITY: ${{ inputs.quality }}
        INPUT_DELETE: ${{ inputs.delete_original }}
      run: |
        echo "🔎 Starting Asset Crusher with Auto-Refactor..."

        SEARCH_EXTENSIONS="-name *.html -o -name *.css -o -name *.js -o -name *.jsx -o -name *.ts -o -name *.tsx -o -name *.vue -o -name *.svelte -o -name *.php -o -name *.md -o -name *.json"

        # --- IMAGES ---
        find . -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" \) -not -path "*/.git/*" | while read img; do
          echo "🔥 Processing: $img"
          
          BASENAME=$(basename "$img")
          DIRNAME=$(dirname "$img")
          FILENAME_NO_EXT="${BASENAME%.*}"
          NEW_NAME="$FILENAME_NO_EXT.webp"
          FULL_NEW_PATH="$DIRNAME/$NEW_NAME"

          cwebp -q "$INPUT_QUALITY" "$img" -o "$FULL_NEW_PATH"
          
          if [ "$INPUT_DELETE" == "true" ]; then
            
            echo "   📝 Refactoring code references for $BASENAME..."
                        
            grep -rTl "$BASENAME" . --exclude-dir=.git | while read source_file; do
               sed -i "s/$BASENAME/$NEW_NAME/g" "$source_file"
               echo "      Start fixing: $source_file"
            done

            rm "$img"
            echo "✅ Converted, Refactored & Deleted: $NEW_NAME"
          else
            echo "✅ Converted (Safe Mode): $NEW_NAME"
          fi
        done

        find . -type f -name "*.mp4" -not -path "*/.git/*" | while read vid; do
          echo "🎬 Processing Video: $vid"
          
          if [ "$INPUT_DELETE" == "true" ]; then
            mv "$vid" "temp_original.mp4"
            ffmpeg -i "temp_original.mp4" -vcodec libx265 -crf 28 "$vid" -y
            rm "temp_original.mp4"
            echo "✅ Video Optimized (Overwritten): $vid"
          else
            OUTPUT_NAME="${vid%.*}_optimized.mp4"
            ffmpeg -i "$vid" -vcodec libx265 -crf 28 "$OUTPUT_NAME" -y
            echo "✅ Video Optimized (New File): $OUTPUT_NAME"
          fi
        done

    - name: Commit Changes
      shell: bash
      env:
        INPUT_DELETE: ${{ inputs.delete_original }}
        MSG: ${{ inputs.commit_message }}
      run: |
        git config --global user.name "Asset-Crusher-Bot"
        git config --global user.email "bot@asset-crusher.io"
        
        git add .
        
        if ! git diff --staged --quiet; then
          echo "🚀 Changes detected..."
          
          if [ "$INPUT_DELETE" == "true" ]; then
            echo "☢️  Mode: Rewrite History (Amend)"
            git commit --amend --no-edit
            git push --force
          else
            echo "🛡️  Mode: Safe Commit"
            git commit -m "$MSG"
            git push
          fi
          
          echo "✅ Assets & Code processed successfully."
        else
          echo "💤 No changes detected."
        fi
